module.exports = [
  {
    name: 'silenthill2',
    title: 'Silent Hill 2',
    releaseDate: 'September 24th, 2001',
    platform: 'PS2, Xbox',
    genre: 'Survival Horror',
    description:
      'Silent Hill 2 is a 2001 survival horror video game published by Konami for the PlayStation 2 and developed by Team Silent, part of Konami Computer Entertainment Tokyo. The second installment in the Silent Hill series, Silent Hill 2 centers on James Sunderland, a widower who journeys to the town of Silent Hill after receiving a letter from his dead wife informing him that she is waiting there for him.',
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyg.png',
  },
  {
    name: 'siren',
    title: 'Siren',
    releaseDate: 'April 20th, 2004',
    platform: 'PS2',
    genre: 'Survival Horror',
    description: `Siren, known as Forbidden Siren in the PAL region, is a survival horror stealth game developed by Project Siren, a development team within Japan Studio, and published by Sony Computer Entertainment for the PlayStation 2 in 2003. The game's plot revolves around an interconnected cast of characters that possess a power which enables them to see and hear what a nearby character sees.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1p0m.png',
  },
  {
    name: 'psychonauts',
    title: 'Psychonauts',
    releaseDate: 'April 19th, 2005',
    platform: 'PS2, Xbox',
    genre: 'Platformer, Action, Adventure',
    description: `Psychonauts is a platform game developed by Double Fine Productions that was first released in 2005. Psychonauts follows the player-character Razputin (Raz), a young boy gifted with psychic abilities who runs away from the circus to try to sneak into a summer camp for those with similar powers to become a "Psychonaut", a spy with psychic abilities. He finds that there is a sinister plot occurring at the camp that only he can stop.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co38t0.png',
  },
  {
    name: 'residentevil2',
    title: 'Resident Evil 2',
    releaseDate: 'January 25th, 2019',
    platform: 'PS4, XB1, PC',
    genre: 'Survival Horror',
    description:
      'In Resident Evil 2, the classic action, tense exploration, and puzzle solving gameplay that defined the Resident Evil series returns. Players join rookie police officer Leon Kennedy and college student Claire Redfield, who are thrust together by a disastrous outbreak in Raccoon City that transformed its population into deadly zombies.',
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ir3.png',
  },
  {
    name: 'grandtheftautosanandreas',
    title: 'Grand Theft Auto: San Andreas',
    releaseDate: 'October 26th, 2004',
    platform: 'PS2, Xbox, PC',
    genre: 'Open-World, Adventure',
    description: `Returning after his mother's murder to the semi-fictional city of Los Santos (based on Los Angeles), Carl Johnson, a former gang banger, must take back the streets for his family and friends by gaining respect and once again gaining control over the streets. However, a story filled with crime, lies and corruption will lead him to trudge the entire state of San Andreas (based on California and Nevada) to rebuild his life.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2lb9.png',
  },
  {
    name: 'metalgearsolid3snakeeater',
    title: 'Metal Gear Solid 3: Snake Eater',
    releaseDate: 'November 17th, 2004',
    platform: 'PS2',
    genre: 'Stealth, Adventure',
    description: `A stealth action/survival game and prequel to Metal Gear Solid 1 (1998) and 2 (2001), MGS3 follows Naked Snake as he trudges through rain forests and swamps in order to clear the name of the American government of suspicion at detonating a nuclear missile within Soviet soil by dispatching the organization behind the act, in a story of shifting allegiances, deception, warfare, mentorship and sexuality.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co29pn.png',
  },
  {
    name: 'hades',
    title: 'Hades',
    releaseDate: 'September 17th, 2020',
    platform: 'XB1, PS4, Switch, PC, PS5, XB1X',
    genre: 'Indie, Rogue-like',
    description: `A rogue-lite hack and slash dungeon crawler in which Zagreus, son of Hades the Greek god of the dead, attempts to escape his home and his oppressive father by fighting the souls of the dead through the various layers of the ever-shifting underworld, while getting to know and forging relationships with its inhabitants.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co39vc.png',
  },
  {
    name: 'thelegendofzeldaocarinaoftime',
    title: 'The Legend of Zelda: Ocarina of Time',
    releaseDate: 'November 21st, 1998',
    platform: 'N64, Wii',
    genre: 'Platform, Adventure',
    description: `A 3D reimagining of the core premise of The Legend of Zelda: A Link to the Past (1991), Ocarina of Time follows Link, the protagonist, as he picks up a sword and leaves behind his humble origins in order to trek across the land of Hyrule, venture into its treacherous dungeons and travel through time itself to fulfill his destiny as the Hero of Time by defeating his enemy Ganondorf and ridding Hyrule of evil.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3nnx.png',
  },
  {
    name: 'discoelysium',
    title: 'Disco Elysium',
    releaseDate: 'October 15th, 2019',
    platform: 'PC, PS4, PS5, Switch, XB1, XB1X',
    genre: 'RPG, Adventure',
    description: `A CRPG in which, waking up in a hotel room a total amnesiac with highly opinionated voices in his head, a middle-aged detective on a murder case inadvertently ends up playing a part in the political dispute between a local labour union and a larger international body, all while struggling to piece together his past, diagnose the nature of the reality around him and come to terms with said reality.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1sfj.png',
  },
  {
    name: 'metroiddread',
    title: 'Metroid Dread',
    releaseDate: 'October 8th, 2021',
    platform: 'Switch',
    genre: 'Adventure, Platform',
    description: `Join intergalactic bounty hunter Samus Aran in her first new 2D Metroid story in 19 years. Samus’ story continues after the events of the Metroid Fusion game when she descends upon planet ZDR to investigate a mysterious transmission sent to the Galactic Federation. The remote planet has become overrun by vicious alien lifeforms and chilling mechanical menaces. Samus is more agile and capable than ever, but can she overcome the inhuman threat stalking the depths of ZDR?`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co39zx.png',
  },
  {
    name: 'killer7',
    title: 'Killer7',
    releaseDate: 'June 9th, 2005',
    platform: 'PS2, Gamecube, PC',
    genre: 'Adventure, Shooter',
    description: `Sneak into a world of underground assassins as Harman Smith, a man who manifests 7 deadly personalities, the killer7. Take control of this distinct murderers' row as they hunt down the sinister Kun Lan to thwart his plan of world dominance.`,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1owa.png',
  },
  {
    name: 'shadowofthecolossus',
    title: 'Shadow of the Colossus',
    releaseDate: 'October 18th, 2005',
    platform: 'PS2',
    genre: 'Adventure, Puzzle, Platform',
    description: `An open-world action/adventure game in which a young wanderer, along with a stolen magical sword and his steed companion, trespasses a cursed land, makes a deal with an ancient being to bring a sacrificial victim back to life, and sets off to fulfill his end of the bargain, which involves tracking down and infiltrating the abodes of sixteen colossi and sacrificing them to achieve his goal.
    `,
    img: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1ozz.png',
  },
];
